name: CD pipeline - Development (authorization backend)

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-push-and-deploy:
    name: Build, Push to GHCR & Deploy
    runs-on: ubuntu-latest
    environment: development 
    
    steps:
      - name: Checkout code (from main branch)
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install production dependencies
        run: npm ci --omit=dev

      - name: Build production app
        run: npm run build

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/auth-service:latest
          
    # - name: Deploy to Development Server (NEXT STEP)
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.DEV_SERVER_HOST }}
    #     username: ${{ secrets.DEV_SERVER_USER }}
    #     key: ${{ secrets.DEV_SERVER_SSH_KEY }}
    #     script: |
    #       echo "Deploying Auth Backend..."
    #       docker pull ghcr.io/${{ github.repository_owner }}/auth-service:latest
    #       docker stop auth-service-dev || true
    #       docker rm auth-service-dev || true
    #       docker run -d --name auth-service-dev -p 8081:8080 --restart always \
    #         --env-file /opt/auth-service/.env \ # .env file on the server
    #         ghcr.io/${{ github.repository_owner }}/auth-service:latest
